version: "3.9"

services:
  petland:
    container_name: petland
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn serve
    env_file:
      - .env
    ports:
      - "3000:3000"
